apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tpbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tpbs
    app.kubernetes.io/part-of: tkrw-pr712-0075-0064-app
  name: devfile-sample-tpbs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tpbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tpbs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-tpbs@sha256:62e139f9f8a516f4d54230bcea5cadcd2eb0449732c818fd25df7d345f560150
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
